Update find_friend_workflow.yml
добавлена проверка для compose файла

diff --git a/.github/workflows/find_friend_workflow.yml b/.github/workflows/find_friend_workflow.yml
--- a/.github/workflows/find_friend_workflow.yml
+++ b/.github/workflows/find_friend_workflow.yml
@@ -95,7 +95,7 @@ jobs:
             echo DB_HOST=${{ secrets.REDIS_HOST }} >> .env
             echo DB_HOST=${{ secrets.REDIS_PORT }} >> .env
             cd infra/prod/
-            docker-compose -f ./docker-compose.prod.yaml config --quiet && printf "OK\n" || printf "ERROR\n" && Exit 1
+            docker-compose -f ./docker-compose.prod.yaml config --quiet && printf "OK\n" || printf "ERROR\n" && exit 1
             docker compose -f ./docker-compose.prod.yaml up -d --build --force-recreate
             docker exec prod-backend-1 python manage.py makemigrations
             docker exec prod-backend-1 python manage.py migrate
