исправление воркфлоу

diff --git a/.github/workflows/find_friend_workflow.yml b/.github/workflows/find_friend_workflow.yml
--- a/.github/workflows/find_friend_workflow.yml
+++ b/.github/workflows/find_friend_workflow.yml
@@ -94,8 +94,16 @@ jobs:
             echo DB_PORT=${{ secrets.DB_PORT }} >> .env
             echo DB_HOST=${{ secrets.REDIS_HOST }} >> .env
             echo DB_HOST=${{ secrets.REDIS_PORT }} >> .env
-            cd infra/prod/
-            docker compose -f ./docker-compose.prod.yaml up -d --build --force-recreate
-            docker exec prod-backend-1 python manage.py makemigrations
-            docker exec prod-backend-1 python manage.py migrate
-            docker exec prod-backend-1 python manage.py collectstatic --no-input
+      - name: run container
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.HOST }}
+          username: ${{ secrets.USER }}
+          key: ${{ secrets.SSH_KEY }}
+          script: |
+              cd /home/${{ secrets.USER }}/infra/prod/
+              docker-compose -f ./docker-compose.prod.yaml config --quiet && printf "OK\n" || printf "ERROR\n" && exit 1
+              docker compose -f ./docker-compose.prod.yaml up -d --build --force-recreate
+              docker exec prod-backend-1 python manage.py makemigrations
+              docker exec prod-backend-1 python manage.py migrate
+              docker exec prod-backend-1 python manage.py collectstatic --no-input
